DATA:
  data_root: data/scannet_3d
  data_root_2d_fused_feature: data/scannet_multiview_openseg
  feature_2d_extractor: openseg
  classes: 20
  aug: True
  voxel_size: 0.02
  input_color: False
  use_shm: False
  
DISTILL:
  arch_3d: MinkUNet18A
  ignore_label: 255
  train_gpu: [0]
  workers: 8  # data loader workers
  batch_size: 8  # batch size for training
  batch_size_val: 1  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.0001
  loss_type: cosine # l1 | cosine
  loop: 5
  epochs: 100
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  manual_seed: 1463
  print_freq: 10
  save_freq: 1
  save_path:
  resume:
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1

TEST:
  split: val  # split in [train, val]
  prompt_eng: True
  mark_no_feature_to_unknown: True
  feature_type: 'ensemble' # 'distill' | 'fusion' | 'ensemble'
  save_feature_as_numpy: False
  vis_pred: False
  vis_gt: False
  test_workers: 8
  test_gpu: [0]
  test_batch_size: 1
  test_repeats: 5
  model_path: 'https://cvg-data.inf.ethz.ch/openscene/models/scannet_openseg.pth.tar'
  save_folder:

Distributed:
  dist_url: tcp://127.0.0.1:6787
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0