DATA:
  data_root: data/nuscenes_3d
  data_root_2d_fused_feature: data/nuscenes_multiview_lseg
  feature_2d_extractor: lseg
  classes: 16
  aug: False
  voxel_size: 0.05
  input_color: False
  use_shm: False
  
DISTILL:
  arch_3d: MinkUNet18A
  ignore_label: 255
  train_gpu: [0,1,2,3]
  workers: 16  # data loader workers
  batch_size: 16  # batch size for training
  batch_size_val: 4  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.0001
  loss_type: cosine # l1 | cosine
  loop: 1
  epochs: 100
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  manual_seed: 3407
  print_freq: 10
  save_freq: 1
  save_path:
  resume:
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1

TEST:
  split: val  # split in [train, val]
  prompt_eng: True
  mark_no_feature_to_unknown: True
  feature_type: 'ensemble' # 'distill' | 'fusion' | 'ensemble'
  save_feature_as_numpy: False
  map_nuscenes_details: True
  vis_input: True
  vis_pred: True
  vis_gt: True
  test_workers: 8
  test_gpu: [0]
  test_batch_size: 4
  test_repeats: 5
  model_path:
  save_folder:

Distributed:
  dist_url: tcp://127.0.0.1:6787
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0